version: '3'
services:


  toxiproxy:
    image: jauderho/toxiproxy
    ports:
      - "8474:8474"
      - "8554:8554"
      - "554:554"
  toxiproxyconfigurator:
    tty: true
    volumes:
      - ./config:/usr/app/src/config/
    build:
      context: .
      dockerfile: .
    depends_on:
      - toxiproxy



