version: '3'
services: 
  toxiproxy: 
    image: ghcr.io/shopify/toxiproxy:2.4.0
    ports: 
      - "8474:8474" 
      - "8554:8554" 
      - "554:554" 
  toxiproxyconfigurator: 
    image: mohamedkrs/toxiproxy
    volumes: 
      - ./config:/usr/app/src/config/ 
    depends_on: 
      - toxiproxy
